### ISSUE TITLE
Request: Apply the subtledoctor hotfix directly to BP in BG

### ISSUE THREAD

**Issue by Endarire** [UnearthedArcana/BP_in_BG#2]
Greetings, @subtledoctor!

I request you apply the subtledoctor hotfix directly to BP in BG.  This way, it's one less thing to track and it's less likely to be deprecated later.

Thankee!

**Comment by subtledoctor** [comment]
But this will (should) generally be installed before MiH. In which case it would be useless, and possibly even cause new bugs. The hotfix needs to be installed after MiH.

**Comment by Endarire** [comment]
@subtledoctor 
When should this hotfix be installed - soon after MiH EQ, soon before EET End, or otherwise?

Thankee!

**Comment by subtledoctor** [comment]
Anytime after MiH EQ. Beyond that, it doesn’t matter.
