### ISSUE TITLE
Another Lore Implementation?

### ISSUE THREAD

**Issue by WithinAmnesia** [UnearthedArcana/BP_in_BG#4]
Option: Start Default Game > Black Pits area come and go freely (can start before or after BG city chapter via some tavern / inn recruiter thing, maybe Ulgoth's Beard or Undercellar) > Complete Black Pits > Baeloth in Larswood with Amnesia / regular Baeloth after Black Pits (effectively requires completing Black Pits to unlock Baeloth)?

**Comment by subtledoctor** [comment]
Playing through the Black Pits precludes you from having Baeloth in your party. 

In the upcoming version you can have Baeloth with you _until_ you go to the Blacks Pits… but not afterward. And there will be a pretty hefty cost for playing this way. _After_ he abducts you and enslaves you and tries to have you killed, there is no forgiving him and kerping him around. That isn’t going to change.

**Comment by subtledoctor** [comment]
Baeloth is the _antagonist_ of the Black Pits. How/why would you have him in your party and also fight against him in that adventure? 

These games are made to be replayed. You play with Baeloth as your party mage one game, and Edwin the next game, and Xan the next game. That is not a problem that needs solving; it’s one of the things people love about the game. This mod functions the same way.

**Comment by WithinAmnesia** [comment]
What if you play an evil party? You are the antagonist too especially if you can freely come and go like the cat person who sells you stuff but chooses to fight with Baeloth. Maybe some people want to see the world burn *with* Baeloth as the antagonist o children of Bhaal the god of murder. What would Sarevok say to you about all this antagonist can't be in the player party eh lol?

**Comment by subtledoctor** [comment]
This is not an “issue” with the mod and an i
proper use of this space. There is a discussion forum at G3 for discussion. Go there if you need to discuss it. 

I have already closed this “issue;” any further comments in this thread will be removed. Thank you for understanding.
